// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// This URL is used only by the Prisma CLI for migrations (`prisma migrate
// deploy`). Migrations need a DIRECT (non-pooled) connection — they don't
// work reliably through a pgbouncer/pooler endpoint — so prefer the
// unpooled connection strings that hosts like Vercel Postgres / Neon inject,
// then fall back to the pooled ones.
//
// Note: this file is loaded for every Prisma CLI command, including
// `prisma generate`, which does not touch the database. Don't throw here if
// the URL is missing — `prisma generate` must keep working without a DB
// connection (e.g. during `npm install`'s postinstall step). Commands that
// actually need the database (like `migrate deploy`) will fail on their own
// with a clear error if the URL is genuinely missing.
const databaseUrl =
  process.env["DIRECT_URL"] || // Prisma-standard name for the direct/migration URL
  process.env["POSTGRES_URL_NON_POOLING"] || // legacy Vercel Postgres (direct)
  process.env["DATABASE_URL_UNPOOLED"] || // Neon native integration (direct)
  process.env["DATABASE_URL"] ||
  process.env["POSTGRES_PRISMA_URL"] ||
  process.env["POSTGRES_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
